### ISSUE TITLE
SSL Patch

### ISSUE THREAD

**Issue by vrst37** [jllopis/docker-mosquitto#12]
Hi Can you please explain your ssl patch? I do not follow what is going on there and would appreciate some clarification as to what the patch is doing.

Thanks

**Comment by jllopis** [comment]
Hi, I'm afraid this is not my patch. It is taken from [Alpine mosquitto package](https://pkgs.alpinelinux.org/package/edge/main/x86_64/mosquitto). It was added by Natanael Copa in commit [175f96b00b04fae415f2ffc39de95bf545da1882](https://git.alpinelinux.org/cgit/aports/commit/?id=175f96b00b04fae415f2ffc39de95bf545da1882). He deserves credit for this.

The only reason I am no using his package directly is to be able to customize the build where needed.

The patch allows mosquitto to be built against LibreSSL. As far as I know, it is due to libressl not supporting opaque structs.
